main: nl.lucasridder.lsurvival.LSurvival
name: L-Survival
version: 1.0
author: LucasRidder
website: lucasridder.nl
api-version: 1.16

commands:
 gamemode:
  aliases: gm
 minigames:
  usage: "/<command>"
 lobby:
  aliases: hub
 kitpvp:
  usage: "/<command>"
 setspawn:
  usage: "/<command>"
 spawn:
  usage: "/<command>"
 stop:
  usage: "/<command>"
 staff:
  usage: "/<command>"
 home:
  usage: "/<command>"
 sethome:
  usage: "/<command>"
 vanish:
  aliases: v
 playtime:
  aliases: pt
 setrank:
  usage: "/<command>"